version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: jodogne/orthanc-plugins
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    volumes:
      - ./OrthancStorage:/srv/OrthancStorage
        #      - ../OrthancDicomWeb/libOrthancDicomWeb.so:/srv/OrthancDicomWeb/libOrthancDicomWeb.so
        #      - ../OrthancDicomWeb/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6
        #      - ../OrthancDicomWeb/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
        #      - ../OrthancPython/libOrthancPython.so:/srv/OrthancPython/libOrthancPython.so
        #      - ../OrthancPython/libpython3.9.so.1.0:/usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0
        #      - ../OrthancPython/libexpat.so.1:/usr/lib/x86_64-linux-gnu/libexpat.so.1
        #      - ./script.py:/srv/script.py
        #      - /usr/lib/python3.9:/usr/lib/python3.9
        #      - ../OrthancWebViewer/libOrthancWebViewer.so:/srv/OrthancWebViewer/libOrthancWebViewer.so
        #      - ../OrthancGdcm/libOrthancGdcm.so:/srv/OrthancGdcm/libOrthancGdcm.so
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

secrets:
  orthanc.json:
    file: orthanc.json
