version: "3.1"
services:
  mc:
    image: nextgenhealthcare/connect
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
    secrets:
      - mirth_properties
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 101:101/tcp
      - 102:102/tcp
      - 103:103/tcp
      - 104:104/tcp
      - 105:105/tcp
      - 106:106/tcp
      - 107:107/tcp
      - 108:108/tcp
      - 109:109/tcp
      - 200:200/tcp
    volumes:
      - ./appdata:/opt/connect/appdata
      - ./health/inbound:/health/inbound
      - ./health/curated:/health/curated
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432

secrets:
  mirth_properties:
    file: mirth.properties
